{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "4c18386e-33b6-456e-afac-693a6d8926f5",
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'pandas'",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mModuleNotFoundError\u001b[39m                       Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[2]\u001b[39m\u001b[32m, line 1\u001b[39m\n\u001b[32m----> \u001b[39m\u001b[32m1\u001b[39m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01mpandas\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mas\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01mpd\u001b[39;00m\n\u001b[32m      3\u001b[39m fake = pd.read_csv(\u001b[33m\"\u001b[39m\u001b[33mFake.csv\u001b[39m\u001b[33m\"\u001b[39m, engine=\u001b[33m\"\u001b[39m\u001b[33mpython\u001b[39m\u001b[33m\"\u001b[39m, on_bad_lines=\u001b[33m\"\u001b[39m\u001b[33mskip\u001b[39m\u001b[33m\"\u001b[39m, encoding=\u001b[33m\"\u001b[39m\u001b[33mlatin1\u001b[39m\u001b[33m\"\u001b[39m, quoting=\u001b[32m3\u001b[39m)\n\u001b[32m      4\u001b[39m true = pd.read_csv(\u001b[33m\"\u001b[39m\u001b[33mTrue.csv\u001b[39m\u001b[33m\"\u001b[39m, engine=\u001b[33m\"\u001b[39m\u001b[33mpython\u001b[39m\u001b[33m\"\u001b[39m, on_bad_lines=\u001b[33m\"\u001b[39m\u001b[33mskip\u001b[39m\u001b[33m\"\u001b[39m, encoding=\u001b[33m\"\u001b[39m\u001b[33mlatin1\u001b[39m\u001b[33m\"\u001b[39m, quoting=\u001b[32m3\u001b[39m)\n",
      "\u001b[31mModuleNotFoundError\u001b[39m: No module named 'pandas'"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "\n",
    "fake = pd.read_csv(\"Fake.csv\", engine=\"python\", on_bad_lines=\"skip\", encoding=\"latin1\", quoting=3)\n",
    "true = pd.read_csv(\"True.csv\", engine=\"python\", on_bad_lines=\"skip\", encoding=\"latin1\", quoting=3)\n",
    "\n",
    "fake['label'] = 0\n",
    "true['label'] = 1\n",
    "\n",
    "df = pd.concat([fake, true]).reset_index(drop=True)\n",
    "df.head()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "438b537c-68ea-4bfb-9e74-39db7fc3427f",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAi4AAAGJCAYAAACtu7gUAAAAOnRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjEwLjcsIGh0dHBzOi8vbWF0cGxvdGxpYi5vcmcvTLEjVAAAAAlwSFlzAAAPYQAAD2EBqD+naQAAO5ZJREFUeJzt3Qm8TfX+//HPMRxUhoyHCFHmIUNSUSInSblpQiFT9aNMSe6VDN1LJCniNkjdKOlmdoWTISGczKKI1M3QYIhk3P/H+/v7rf3f+0zOOc5x9srr+Xgs+6y1vnvttdce1nt/hyUqEAgEDAAAwAeyZfUOAAAApBbBBQAA+AbBBQAA+AbBBQAA+AbBBQAA+AbBBQAA+AbBBQAA+AbBBQAA+AbBBQAA+AbBBUjGkiVLLCoqyj766CPzg/3799u9995rhQoVcvv98ssvZ/pj6nG6d++e6Y/zZ7R79253/CZNmpTVu2IX+zFVed1P90fkI7ggS3lfGLlz57b//ve/idbfcsstVrVq1SzZN7/p1auXffLJJ9a/f3/717/+ZbfffnuyZXXMk5piYmLsYnz/eVOOHDnsiiuusA4dOiT5fszKAK0pPj4+0Xrt62WXXWZ+cubMGStRooR7Tv/5z3/SfP8pU6ZckGCOyJQjq3cAkBMnTtjw4cPt1Vdfzepd8a1PP/3U7r77bnvqqadSVf62226zdu3ahS3LkyePXYyGDBliZcuWtT/++MNWrVrlAs3y5ctt8+bNLlRHikGDBtns2bPtz/Be3bt3r5UpU8YmT55szZo1S3Nw0WvTs2fPsOWlS5e248ePW86cOTN4jxFJCC6ICDVr1rQ33njD1Rbol9jF5NixY3bppZee93YOHDhgBQoUSHX5a665xh566KHzftw/A50469Sp4/7u3LmzFS5c2F544QWbNWuW3X///RYpn5E5c+bYl19+abVq1TI/e++999xzaN++vf31r39N9WfgXOW82lv8udFUhIigLy9VH6vWJb1t2FquX6Qe/a1lX3/9tTtB58+f34oUKWLPPvus6T9F//77710NRb58+VwTyahRo5J8TO2X9k9l9KV51113ufsm9MUXX7jmGT3OJZdcYjfffLN9/vnnYWW8fdq6dau1adPGLr/8crvppptSfM7ffvut3XfffVawYEG33euvv97mzp2bqLlDz2ncuHHBZoXz8eKLL9oNN9zg+suoFqZ27dqp7uvz/PPPW7Zs2cJqz9Qc0KBBA3f88ubNa82bN7ctW7akuJ21a9e65/HOO+8kWqcmMa3TiVx+++039+tbv+Bz5cplRYsWdTVKOsmnh/ZVdu7cGbZ827Ztrh+RXgudIBV2FG5C/frrr67Wq1q1aq4JR+8vBaMNGzbY+XjiiSfc+yX0PZ6Scx1z7beO4caNG4PL/v3vf7tl99xzT9i2KlWqZA888EBwfuHChe59q6Cs51ihQgX3GUkN1YhMnz7dHnzwQRcKNT9z5sxkm8D0Gtxxxx3uObRt29Y1H+v9/9133wXf63rdU/p+0Oumx9LnX+9n7e/f/va38z6Gsm/fPnvkkUesZMmS7r1XvHhx971Cf5nMQ3BBRFA1vZotVOvy448/Zui29YV79uxZF4rq1avnTqxqH9eJTf0Z9Mu6fPny7mSzbNmyRPf/+9//7r4o+/XrZ08++aT70m7SpIn7wg2t+m7YsKEdOXLEnnvuOfvHP/5hhw4dsltvvdVWr16daJsKIr///rsr16VLlxQ73CpA6ET9P//zP25f1Jyh8KQvf9Hjqk+L6Dnpb28+JdrOzz//HDapyU7GjBlj1157rWtC0T6q74f2OTQwJWXAgAE2cOBA++c//+lOtKJ90Re+TkI61gqOCm468aX05a5QcNVVV9mHH36YaN3UqVPdSTw2NtbNP/bYYzZ+/Hhr1aqVvfbaa+611Anqq6++svTw9kuP4dEJS6FR23zmmWdc0NUJrWXLlsHXwguaM2bMsDvvvNNeeukl69u3r23atMkF2fN5bysAqR+TmorOFchSc8z1t07yoe/5zz77zIVONZN5fvrpJ3fi1/vMOw56bnqv6P2h46D3Y8KQnhwFpqNHj7rgoh8DCiJqLkrK6dOn3WusIKowrddXgUO1T6oV897rKfV3UTDT516fUX3W9N7Wa3auJrfUvm+1T3r9FV703tN3hIL0nj17UnU8kA4BIAu9/fbbAb0N16xZE9i5c2cgR44cgSeffDK4/uabbw5UqVIlOL9r1y5XXvdLSMufe+654Lz+1rKuXbsGl50+fTpQsmTJQFRUVGD48OHB5QcPHgzkyZMn0L59++CyxYsXu/tfccUVgSNHjgSXf/jhh275mDFj3PzZs2cDV199dSA2Ntb97fn9998DZcuWDdx2222J9ql169apOj49e/Z05T/77LPgst9++81tt0yZMoEzZ86EPf9u3bqlarsqm9TkHVfte6iTJ08GqlatGrj11lsTbcd7zD59+gSyZcsWmDRpUti+FihQINClS5ew++3bty+QP3/+RMsT6t+/fyBnzpyBX3/9NbjsxIkTbpsdO3YMLtO2Uvvck3r/LVq0KPDTTz8Fvv/++8BHH30UKFKkSCBXrlxu3tO4ceNAtWrVAn/88UdwmV7vG264wb3+Hq0PfV289622N2TIkFS9l0N578Np06YFDh06FLj88ssDd911V3C93rOXXnppuo65Plv3339/cL5WrVqB++67zz3eV1995ZZ9/PHHbn7Dhg1ufvTo0W5exys97rzzzsCNN94YnH/99dfd5/7AgQNh5fS89DjPPPNMom00b948ULp06UTLkzqmDRs2DOTNmzfw3XffhZUN/ax67wPdPy3HUN8but/IkSPTcSSQXtS4IGLo1/XDDz9sr7/+uuu4l1HUZ8GTPXt290te59xOnToFl6vKW9XH+rWckGqCVE3sUVOBqoPnzZvn5tevX2/ffPONa/r55ZdfgrUXao9v3Lix+0WrGp9QqiFIDT3GddddF9acpF+AXbt2db/69AswvVSdrdqj0MmrwQjtpHvw4EE7fPiwqzJP6pe+jqWGROuXrPouqN+CR9tUzVPr1q3Danb0OuhX8OLFi89ZW3bq1Cn7+OOPg8sWLFjgthnadKHXT0116a3RUA2amhFKlSrlXl/VpKhmQNX/XvOPfrGruUG/pr3noddbx0yvvzcKSc0FqrXwmhlVxmtOSW/TlUfNkGoS076tW7cuyTJpOeZ6TVXLInpeas7Se0u1Gd5y3er4eqP7vH5Uat5J+L4+Fx0L1R5q30JrLFTzk1TNmjz++OOWXqot0uevY8eOduWVV4atS6k5NbXHUJ+T6OhoN/JLnxNcGAQXRBQ1Nah6+Fx9XdIi4ReWvvzVP0FfzgmXJ/Xlc/XVVyf6wlPTklddrJOW6IStk1/o9Oabb7oqdZ34EzaNpYba8XXCS0h9Drz16aWTsk7YoZMCmajviJpFdJzUn0PPRU0xCZ+HvPvuu65vjfq0hJ6QQo+NmswSHhsFEHUoTkmNGjWsYsWKrmnIo7/12mmbnhEjRrhRJgoeCnrqB5JUCE2O9l8nK/XjUX8KnaQUQDw7duxwAU3NBQmfh5oGxXsuOpmPHj3avW+0De2ryqnJIqnjl1Y9evRw4SG5vi5pOeYKLvqRoOe3YsUK996uX79+WKDR7Y033hgMYwqMmtcPgmLFirkmH4WO1IQYvXYKomqG1GNqUihUGEiquUhNlF54TA/vPZDWSyqk9hjq9VUzkvrC6FioOU3vRfV7QeZhVBEirtZFHWlV66J+BAkl9ytJv2yTo19JqVkm/9v6kTbeF/bIkSNd23tSEl5nI5KHHetEpT4L+hJWm73CjIaXvv32224YakI6ianWaezYsa5GQkEn4bFRf4GkrhGjE9O56ESpvj0KE6r5Um2DAlLoffW4Otmqr4FOLHotdEJRTU1qhtoq7HijitT/QTVcqkHbvn27e+2856G+M16tVEIKs6I+QQo4+pU/dOhQdzx00ldNSVprKFKqdVFwSarWJS3H3KvJU62ETvIa6aPaJh3LV155xfVF0WPo+Ie+d1VetQ7q8zR//nwXSHSS17FP7rMlXjjReyYp2gd9B3hCa68upLQcQ70WLVq0cP2aVJuk137YsGGuhk4BDRmP4IKIrHVRk4NOPAl5nSVVjRvqfGoeUvvrKzTc6Jdi9erV3Xy5cuWCnSdVa5GRdF0KnTwTUmdJb31G08gS1bToSzi01kHBJbkTtn5lqpOlRlXFxcUFm9a8Y6POlek9NgougwcPdvulX7XqAK1f+QkpYKkDsyb9ItZJWCfctF4jRCdenXgaNWrkwpgCtHcyVYA71/NQrY3u+9Zbb4Ut13s2YS1feulkqQ6pOi4Jh8Cn5ZirNlKTwqpCgzeaSqG1d+/eNm3aNPejwOuY61GYUDOoJnVAVlhTp1mFmeQec9euXa5WR82K6qicMCiomVjBWJ//c0ntqDnvdVNtXFqk9X2r8n369HGTvi/0A0adlvU9hoxHUxEijr4EVOuikSkJq1wVDvTln3D0j2oGMouaQtT+H3piUvW6d0LUUGHts0Y96BdqUu3s6aVmC41KWrlyZXCZ+s6oRkpDQCtXrmwZTSdunRhCa7HULKZflMlRiFN/HI240a9Pb8SVaif0munEpiaC9BwbNYtpaLF+1WtSQAk9kWo/EzbB6ISj6wF5o6TSSiFMtTAKBxp9pe1pmd6TSfW/Cn0eOn4Ja+4UADLySrxerYv6mai2K1Raj7nCimoH9D7zgotOvAqfarL1hsN71LSTkFfTmNLx9mpbnn76adePKHRSjZnCTHKjixJSrVBqmt3UtKP3ysSJExON8kmpdjW1x1AjA/X+CKXvAh279L73cG7UuCAi6debqmlV21ClSpWwdWpb1xeqblW9rxCja7VkFlX1q0pdwx01PFknM9UyeMOY9etTfVkUZLSvKqdh1jpR6ReovgDTe7VT/dp///333bY1zFL7ouua6NeraiAyoxpdQ0D1K1q1J2ouUe2F+oDoOYde8yMh9YnRiVRhSycjBR09d/WN0a9p1YCopkQnE51E1MygJgPVaqSm1kXDrFUTpE7Voc9boVL9IPSY6hOjpp1FixbZmjVrkr02T2poGLOGgOuaIOpMrWOg94FClF57/ZrX+0Gh8ocffghep0VDhTVMWO8DDWXXUGidkEObQDKC+rqoL40eN/SibGk95gor2j+FVa/pSOHLG4avwKYOqB49N33m9D5RjZ/eH/rhoNcgpWsS6TEUcNQPKSlqntQQ+tRcYE9BSiFWtUJ169Z1r7kCc1LU5KX90jbV8Vj9yxTEdSwShr60HkN976jWScFLPyLUhKTmSr0vkqoVRAZJ93gkIIOHQyfkDYcMHQ7tDdXt1KmTG5aoYY4azqmhlMkNh044bDPh8NHkhl57w1Dff/99Nyy3aNGibsi0hmImHFop69atC9xzzz2BQoUKuaGvGq6pfYuLizvnPqVEw8TvvfdeNzwzd+7cgeuuuy4wZ86cROXSOhw6pbJvvfWWG+Kr51GxYkX3Onn7fq7tzJw50w1vfeCBB4LDgnUsNVxcr5meQ7ly5QIdOnQIrF27NlX7+8033wSHbC9fvjxsnYZH9+3bN1CjRg33ftBrq79fe+2183r/ad+1n5o0jN57Ldq1axeIiYlxw7Q1VF7DezWEOnQ4tIaGFy9e3L1fNPR35cqV7v2l6XyGQyfkvSZJvZ9Te8y3bNnitlGpUqWw5c8//7xb/uyzz4Yt1/v57rvvDpQoUSIQHR3tbjW8/+uvv072OcTHxye5rVC7d+92ZXr16pXi51SOHj0aaNOmjftM6D7e0OjkjunmzZsDf/nLX4KfoQoVKoTtS8Lh0Kk9hj///LN7/+szon1VuXr16rlLJiDzROmfjApBAAAAmYk+LgAAwDcILgAAwDcILgAAwDcILgAAwDcILgAAwDcILgAAwDe4AF0G0SWr9T/T6oqJqb0cNQAAMHclY11MUle8PteFNQkuGUShJbkrQgIAgHP7/vvvz/k/ghNcMoj3n8rpoOty0QAAIHX0n6fqx793Lk0JwSWDeM1DCi0EFwAA0i41XS3onAsAAHyD4AIAAHyD4AIAAHyD4AIAAHyD4AIAAHyD4AIAAHyD4AIAAHyD4AIAAHyD4AIAAHyD4AIAAHyD4AIAAHyD/6vIJ2r3fTerdwHIdPEj22X1LgCIcAQXAMgA/LjAxSA+An5c0FQEAAB8g+ACAAB8g+ACAAB8g+ACAAB8g+ACAAB8g+ACAAB8I0uDy7Bhw6xu3bqWN29eK1q0qLVs2dK2b98eVuaPP/6wbt26WaFCheyyyy6zVq1a2f79+8PK7Nmzx5o3b26XXHKJ207fvn3t9OnTYWWWLFlitWrVsly5cln58uVt0qRJifZn3LhxVqZMGcudO7fVq1fPVq9enUnPHAAA+C64LF261IWSVatW2cKFC+3UqVPWtGlTO3bsWLBMr169bPbs2TZt2jRX/scff7R77rknuP7MmTMutJw8edJWrFhh77zzjgslAwcODJbZtWuXK9OoUSNbv3699ezZ0zp37myffPJJsMzUqVOtd+/e9txzz9mXX35pNWrUsNjYWDtw4MAFPCIAACAlUYFAIGAR4qeffnI1JgooDRs2tMOHD1uRIkVsypQpdu+997oy27Zts0qVKtnKlSvt+uuvt//85z925513ukBTrFgxV2bChAnWr18/t73o6Gj399y5c23z5s3Bx3rwwQft0KFDNn/+fDevGhbV/owdO9bNnz171kqVKmVPPPGEPfPMM+fc9yNHjlj+/PndPufLly/Djw0Xt8LFIBIubpVefEZxMYjPpM9oWs6hEdXHRTssBQsWdLfx8fGuFqZJkybBMhUrVrQrr7zSBRfRbbVq1YKhRVRTooOwZcuWYJnQbXhlvG2otkaPFVomW7Zsbt4rk9CJEyfcY4ROAAAgc0VMcFENh5pwbrzxRqtatapbtm/fPldjUqBAgbCyCila55UJDS3eem9dSmUUNo4fP24///yza3JKqoy3jaT65ygdepNqZwAAwEUSXNTXRU05H3zwgflB//79XQ2RN33//fdZvUsAAPzpRcR/sti9e3ebM2eOLVu2zEqWLBlcHhMT45px1BcltNZFo4q0ziuTcPSPN+ootEzCkUiaVztanjx5LHv27G5Kqoy3jYQ0OkkTAAC4SGpc1C9YoWX69On26aefWtmyZcPW165d23LmzGlxcXHBZRoureHP9evXd/O63bRpU9joH41QUiipXLlysEzoNrwy3jbUHKXHCi2jpivNe2UAAMBFXuOi5iGNGJo5c6a7lovXn0R9RlQTottOnTq5YcrqsKswolE+ChMaUSQaPq2A8vDDD9uIESPcNgYMGOC27dWIPPbYY2600NNPP20dO3Z0IenDDz90I408eoz27dtbnTp17LrrrrOXX37ZDct+5JFHsujoAACAiAou48ePd7e33HJL2PK3337bOnTo4P4ePXq0G+GjC89pJI9GA7322mvBsmriUTPT448/7gLNpZde6gLIkCFDgmVUk6OQomvCjBkzxjVHvfnmm25bngceeMANn9b1XxR+atas6YZKJ+ywCwAAsk5EXcfFz7iOC3D+uI4LENniuY4LAABA6hFcAACAbxBcAACAbxBcAACAbxBcAACAbxBcAACAbxBcAACAbxBcAACAbxBcAACAbxBcAACAbxBcAACAbxBcAACAbxBcAACAbxBcAACAbxBcAACAbxBcAACAbxBcAACAbxBcAACAbxBcAACAbxBcAACAbxBcAACAbxBcAACAbxBcAACAbxBcAACAb2RpcFm2bJm1aNHCSpQoYVFRUTZjxoyw9VqW1DRy5MhgmTJlyiRaP3z48LDtbNy40Ro0aGC5c+e2UqVK2YgRIxLty7Rp06xixYquTLVq1WzevHmZ+MwBAIDvgsuxY8esRo0aNm7cuCTX7927N2yaOHGiCyatWrUKKzdkyJCwck888URw3ZEjR6xp06ZWunRpi4+Pd6Fn0KBB9vrrrwfLrFixwlq3bm2dOnWydevWWcuWLd20efPmTHz2AAAgrXJYFmrWrJmbkhMTExM2P3PmTGvUqJFdddVVYcvz5s2bqKxn8uTJdvLkSRd6oqOjrUqVKrZ+/Xp76aWXrGvXrq7MmDFj7Pbbb7e+ffu6+aFDh9rChQtt7NixNmHChAx4pgAA4KLq47J//36bO3euqxVJSE1DhQoVsmuvvdbVqJw+fTq4buXKldawYUMXWjyxsbG2fft2O3jwYLBMkyZNwrapMlqenBMnTrjanNAJAAD8iWtc0uKdd95xNSv33HNP2PInn3zSatWqZQULFnRNPv3793fNRapRkX379lnZsmXD7lOsWLHgussvv9zdestCy2h5coYNG2aDBw/OwGcIAAD+NMFFTT1t27Z1nWdD9e7dO/h39erVXc3Ko48+6oJFrly5Mm1/FJBCH1s1Lur4CwAALvLg8tlnn7mmnalTp56zbL169VxT0e7du61ChQqu74uamUJ5816/mOTKJNdvRhSKMjMYAQAAn/Zxeeutt6x27dpuBNK5qONttmzZrGjRom6+fv36btj1qVOngmXU8VahRs1EXpm4uLiw7aiMlgMAgMiRpcHl6NGjLmhokl27drm/9+zZE9YEo2usdO7cOdH91Xn25Zdftg0bNti3337rRhD16tXLHnrooWAoadOmjWs+UqfeLVu2uFobjSIKbebp0aOHzZ8/30aNGmXbtm1zw6XXrl1r3bt3vyDHAQAA+KCpSOFAw5s9Xpho3769TZo0yf39wQcfWCAQcNdZSUhNNVqvoKFRPuqEq+ASGkry589vCxYssG7durlam8KFC9vAgQODQ6HlhhtusClTptiAAQPsr3/9q1199dXuYnhVq1bN5CMAAADSIiqgVIDzppohhaTDhw9bvnz5Mnz7tfu+m+HbBCJN/Mh25ld8RnExiM+kz2hazqG+6OMCAAAgBBcAAOAbBBcAAOAbBBcAAOAbBBcAAOAbBBcAAOAbBBcAAOAbBBcAAOAbBBcAAOAbBBcAAOAbBBcAAOAbBBcAAOAbBBcAAOAbBBcAAOAbBBcAAOAbBBcAAOAbBBcAAOAbBBcAAOAbBBcAAOAbBBcAAOAbBBcAAOAbBBcAAOAbBBcAAOAbBBcAAOAbBBcAAOAbWRpcli1bZi1atLASJUpYVFSUzZgxI2x9hw4d3PLQ6fbbbw8r8+uvv1rbtm0tX758VqBAAevUqZMdPXo0rMzGjRutQYMGljt3bitVqpSNGDEi0b5MmzbNKlas6MpUq1bN5s2bl0nPGgAA+DK4HDt2zGrUqGHjxo1LtoyCyt69e4PT+++/H7ZeoWXLli22cOFCmzNnjgtDXbt2Da4/cuSINW3a1EqXLm3x8fE2cuRIGzRokL3++uvBMitWrLDWrVu70LNu3Tpr2bKlmzZv3pxJzxwAAKRHDstCzZo1c1NKcuXKZTExMUmu++qrr2z+/Pm2Zs0aq1Onjlv26quv2h133GEvvviiq8mZPHmynTx50iZOnGjR0dFWpUoVW79+vb300kvBgDNmzBgXkPr27evmhw4d6oLQ2LFjbcKECUk+9okTJ9wUGpAAAMBF3sdlyZIlVrRoUatQoYI9/vjj9ssvvwTXrVy50jUPeaFFmjRpYtmyZbMvvvgiWKZhw4YutHhiY2Nt+/btdvDgwWAZ3S+Uymh5coYNG2b58+cPTmqCAgAAF3FwUS3Iu+++a3FxcfbCCy/Y0qVLXQ3NmTNn3Pp9+/a5UBMqR44cVrBgQbfOK1OsWLGwMt78ucp465PSv39/O3z4cHD6/vvvM+hZAwCAiGwqOpcHH3ww+Lc6zFavXt3KlSvnamEaN26cpfumJixNAADgwonoGpeErrrqKitcuLDt2LHDzavvy4EDB8LKnD592o008vrF6Hb//v1hZbz5c5VJrm8NAADIGr4KLj/88IPr41K8eHE3X79+fTt06JAbLeT59NNP7ezZs1avXr1gGY00OnXqVLCMOt6qz8zll18eLKPmqFAqo+UAACByZGlw0fVWNMJHk+zatcv9vWfPHrdOo3xWrVplu3fvdsHi7rvvtvLly7uOs1KpUiXXD6ZLly62evVq+/zzz6179+6uiUkjiqRNmzauY66GOmvY9NSpU90oot69ewf3o0ePHm500qhRo2zbtm1uuPTatWvdtgAAQOTI0uCicHDttde6SRQm9PfAgQMte/bs7sJxd911l11zzTUueNSuXds+++yzsL4lGu6sC8epz4uGQd90001h12jRiJ8FCxa4UKT79+nTx20/9FovN9xwg02ZMsXdT9eV+eijj9zF8KpWrXqBjwgAAEhJVCAQCKRYAqmi67goJGmEka7im9Fq9303w7cJRJr4ke3Mr/iM4mIQn0mf0bScQ33VxwUAAFzcCC4AAMA3CC4AAMA3CC4AAMA3CC4AAMA3CC4AAMA3CC4AAMA3CC4AAMA3CC4AAMA3CC4AAMA3CC4AAMA3CC4AAMA3CC4AAMA3CC4AAMA3CC4AAMA3CC4AAMA3CC4AAMA3CC4AAMA3CC4AAMA3CC4AAMA3CC4AAMA3CC4AAMA3CC4AAMA3CC4AAMA3sjS4LFu2zFq0aGElSpSwqKgomzFjRnDdqVOnrF+/flatWjW79NJLXZl27drZjz/+GLaNMmXKuPuGTsOHDw8rs3HjRmvQoIHlzp3bSpUqZSNGjEi0L9OmTbOKFSu6MnrMefPmZeIzBwAAvgsux44dsxo1ati4ceMSrfv999/tyy+/tGeffdbdfvzxx7Z9+3a76667EpUdMmSI7d27Nzg98cQTwXVHjhyxpk2bWunSpS0+Pt5GjhxpgwYNstdffz1YZsWKFda6dWvr1KmTrVu3zlq2bOmmzZs3Z+KzBwAAaZXDslCzZs3clJT8+fPbwoULw5aNHTvWrrvuOtuzZ49deeWVweV58+a1mJiYJLczefJkO3nypE2cONGio6OtSpUqtn79envppZesa9eursyYMWPs9ttvt759+7r5oUOHusfW402YMCEDnzEAALho+rgcPnzYNQUVKFAgbLmahgoVKmTXXnutq1E5ffp0cN3KlSutYcOGLrR4YmNjXe3NwYMHg2WaNGkStk2V0fLknDhxwtXmhE4AAOBPXOOSFn/88Yfr86ImnXz58gWXP/nkk1arVi0rWLCga/Lp37+/ay5SjYrs27fPypYtG7atYsWKBdddfvnl7tZbFlpGy5MzbNgwGzx4cAY/SwAA4Pvgoo66999/vwUCARs/fnzYut69ewf/rl69uqtZefTRR12wyJUrV6btkwJS6GOrxkUdfwEAwEUcXLzQ8t1339mnn34aVtuSlHr16rmmot27d1uFChVc35f9+/eHlfHmvX4xyZVJrt+MKBRlZjACAAA+6+PihZZvvvnGFi1a5PqxnIs63mbLls2KFi3q5uvXr++GXWtbHnW8VahRM5FXJi4uLmw7KqPlAAAgcmRpjcvRo0dtx44dwfldu3a54KH+KsWLF7d7773XDYWeM2eOnTlzJtjnROvVJKTOs1988YU1atTIjSzSfK9eveyhhx4KhpI2bdq4viga6qw+MhrirFFEo0ePDj5ujx497Oabb7ZRo0ZZ8+bN7YMPPrC1a9eGDZkGAAA+rXG59dZb7dChQ4mWq5+H1qWWwoFGAmkS9RnR3wMHDrT//ve/NmvWLPvhhx+sZs2aLsh4kzrhippqFDIUOjTM+e9//7sLLqGBQ8OqFyxY4EJR7dq1rU+fPm773lBoueGGG2zKlCnufrquzEcffeQuhle1atX0HB4AAJBJogLq8ZpGaopR7YfXHOM5cOCAXXHFFWHNMhcLhTaFJA3ZPlc/nPSo3ffdDN8mEGniR7Yzv+IziotBfCZ9RtNyDk1TU5Eune/ZunVr2HBhNeXMnz/fBRcAAIDMkKbgoiYb7/8DSqpJKE+ePPbqq69m5P4BAACkL7ion4halq666ipbvXq1FSlSJLhOnWXVdJQ9e/a0bBIAACBzgov+o0I5e/ZsWu4GAACQtcOhdW2VxYsXuw65CYOMRu0AAABktHQFlzfeeMMef/xxK1y4sLu6rPq8ePQ3wQUAAERMcHn++efdNVN0QTcAAICIvgDdwYMH7b777sv4vQEAAMjo4KLQoqvRAgAARHxTUfny5e3ZZ5+1VatWWbVq1Sxnzpxh65988smM2j8AAIDzCy76P30uu+wyW7p0qZtCqXMuwQUAAERMcNGF6AAAAHzRxwUAAMA3NS4dO3ZMcf3EiRPTuz8AAAAZG1w0HDrUqVOnbPPmzXbo0KEk//NFAACALAsu06dPT7RMl/3X1XTLlSuXEfsFAACQeX1csmXLZr1797bRo0dn1CYBAAAyr3Puzp077fTp0xm5SQAAgPNrKlLNSqhAIGB79+61uXPnWvv27dOzSQAAgMwJLuvWrUvUTFSkSBEbNWrUOUccAQAAXNDgsnjx4nQ/IAAAwAUNLp6ffvrJtm/f7v6uUKGCq3UBAACIqM65x44dc01CxYsXt4YNG7qpRIkS1qlTJ/v9998zfi8BAADSG1zUOVf/ueLs2bPdRec0zZw50y3r06dPxu8lAABAeoPLv//9b3vrrbesWbNmli9fPjfdcccd9sYbb9hHH32U6u0sW7bMWrRo4Wpr9L9Kz5gxI9FopYEDB7qanTx58liTJk3sm2++CSvz66+/Wtu2bd0+FChQwNX6HD16NKzMxo0brUGDBpY7d24rVaqUjRgxItG+TJs2zSpWrOjKVKtWzebNm5fm4wIAACIwuKg5qFixYomWFy1aNE1NRWpyqlGjho0bNy7J9QoYr7zyik2YMMG++OILu/TSSy02Ntb++OOPYBmFli1bttjChQttzpw5Lgx17do1uP7IkSPWtGlTK126tMXHx9vIkSNt0KBB9vrrrwfLrFixwlq3bu1Cj0ZMtWzZ0k36bwwAAEDkiAqoWiONGjdubIUKFbJ3333X1VDI8ePH3TVcVAOyaNGitO9IVJT7rwQUGES7pZoYNT099dRTbtnhw4ddYJo0aZI9+OCD9tVXX1nlypVtzZo1VqdOHVdm/vz5rvbnhx9+cPcfP368/e1vf7N9+/ZZdHS0K/PMM8+42p1t27a5+QceeMCFKAUfz/XXX281a9Z0oSk1FJDy58/v9lG1Pxmtdt93M3ybQKSJH9nO/IrPKC4G8Zn0GU3LOTRdNS4vv/yyff7551ayZEkXYjSpCUbLxowZYxlh165dLmyoecijJ1WvXj1buXKlm9etmoe80CIqr+vKqIbGK6POw15oEdXaaDSU959Fqkzo43hlvMdJyokTJ9yBDp0AAEAEDodWHxD1NZk8eXKw1kJNLWq2UV+UjKDQIgmbpDTvrdOtmqdC5ciRwwoWLBhWpmzZsom24a27/PLL3W1Kj5OUYcOG2eDBg8/rOQIAgAsQXHTS1om9S5cuYcsnTpzoru3Sr18/+7Pr379/2H99oBoX1ToBAIDMk66mon/+859uBE5CVapUSXWfkHOJiYlxt/v37w9brnlvnW4PHDgQtl7/yaP62YSWSWoboY+RXBlvfVJy5coVHFHlTQAAIAKDi5pQNEQ5IV05V//ZYkZQ846CQ1xcXFithvqu1K9f383rVteQ0Wghz6effmpnz551fWG8MhppdOrUqWAZjUDSlX7VTOSVCX0cr4z3OAAAwMfBxeuIm5CWaSRPaul6K+vXr3eT1yFXf+/Zs8eNMurZs6c9//zzNmvWLNu0aZO1a9fObd8beVSpUiW7/fbbXZPV6tWr3eN3797djTjy9qNNmzauY66GOmvY9NSpU10H4tBmnh49erjRSPpPItVnR8Ol165d67YFAAB83sdFQUGhQrUYt956q1umGounn346TVfOVTho1KhRcN4LExpWrSHP2p6GKeu6LKpZuemmm1zA8IZgizoIK2BoZJNGE7Vq1cpd+yV0JNKCBQusW7duVrt2bStcuLC7qF3otV5uuOEGmzJlig0YMMD++te/2tVXX+2GS1etWjU9hwcAAETSdVx0F10LRQHh5MmTbpnChDrlKhRcjLiOC3D+uI4LENniI+A6LumqcVEzzgsvvGDPPvusuwichkCrlkIdVgEAADJLuoKL57LLLrO6detm3N4AAABkdOdcAACArEBwAQAAvkFwAQAAvkFwAQAAvkFwAQAAvkFwAQAAvkFwAQAAvkFwAQAAvkFwAQAAvkFwAQAAvkFwAQAAvkFwAQAAvkFwAQAAvkFwAQAAvkFwAQAAvkFwAQAAvkFwAQAAvkFwAQAAvkFwAQAAvkFwAQAAvkFwAQAAvkFwAQAAvhHxwaVMmTIWFRWVaOrWrZtbf8sttyRa99hjj4VtY8+ePda8eXO75JJLrGjRota3b187ffp0WJklS5ZYrVq1LFeuXFa+fHmbNGnSBX2eAADg3HJYhFuzZo2dOXMmOL9582a77bbb7L777gsu69Kliw0ZMiQ4r4Di0X0VWmJiYmzFihW2d+9ea9euneXMmdP+8Y9/uDK7du1yZRR4Jk+ebHFxcda5c2crXry4xcbGXrDnCgAAfB5cihQpEjY/fPhwK1eunN18881hQUXBJCkLFiywrVu32qJFi6xYsWJWs2ZNGzp0qPXr188GDRpk0dHRNmHCBCtbtqyNGjXK3adSpUq2fPlyGz16NMEFAIAIEvFNRaFOnjxp7733nnXs2NE1CXlUS1K4cGGrWrWq9e/f337//ffgupUrV1q1atVcaPEojBw5csS2bNkSLNOkSZOwx1IZLU/OiRMn3DZCJwAAcJHXuISaMWOGHTp0yDp06BBc1qZNGytdurSVKFHCNm7c6GpStm/fbh9//LFbv2/fvrDQIt681qVURmHk+PHjlidPnkT7MmzYMBs8eHCmPE8AAPAnCC5vvfWWNWvWzIUUT9euXYN/q2ZF/VIaN25sO3fudE1KmUU1O7179w7OK+SUKlUq0x4PAAD4KLh89913rp+KV5OSnHr16rnbHTt2uOCivi+rV68OK7N//3536/WL0a23LLRMvnz5kqxtEY0+0gQAAC4c3/Rxefvtt91QZo3+Scn69evdrWpepH79+rZp0yY7cOBAsMzChQtdKKlcuXKwjEYShVIZLQcAAJHDF8Hl7NmzLri0b9/ecuT4/5VEag7SCKH4+HjbvXu3zZo1yw11btiwoVWvXt2Vadq0qQsoDz/8sG3YsME++eQTGzBggLsOjFdjomHQ3377rT399NO2bds2e+211+zDDz+0Xr16ZdlzBgAAPg0uaiLSReQ0miiUhjJrncJJxYoVrU+fPtaqVSubPXt2sEz27Nltzpw57lY1KA899JALN6HXfdFQ6Llz57palho1arhh0W+++SZDoQEAiDC+6OOiYBIIBBItV2fYpUuXnvP+GnU0b968FMvoCrzr1q07r/0EAACZyxc1LgAAAEJwAQAAvkFwAQAAvkFwAQAAvkFwAQAAvkFwAQAAvkFwAQAAvkFwAQAAvkFwAQAAvkFwAQAAvkFwAQAAvkFwAQAAvkFwAQAAvkFwAQAAvkFwAQAAvkFwAQAAvkFwAQAAvkFwAQAAvkFwAQAAvkFwAQAAvkFwAQAAvkFwAQAAvkFwAQAAvkFwAQAAvhHRwWXQoEEWFRUVNlWsWDG4/o8//rBu3bpZoUKF7LLLLrNWrVrZ/v37w7axZ88ea968uV1yySVWtGhR69u3r50+fTqszJIlS6xWrVqWK1cuK1++vE2aNOmCPUcAAPAnCS5SpUoV27t3b3Bavnx5cF2vXr1s9uzZNm3aNFu6dKn9+OOPds899wTXnzlzxoWWkydP2ooVK+ydd95xoWTgwIHBMrt27XJlGjVqZOvXr7eePXta586d7ZNPPrngzxUAAKQsh0W4HDlyWExMTKLlhw8ftrfeesumTJlit956q1v29ttvW6VKlWzVqlV2/fXX24IFC2zr1q22aNEiK1asmNWsWdOGDh1q/fr1c7U50dHRNmHCBCtbtqyNGjXKbUP3VzgaPXq0xcbGXvDnCwAAfFzj8s0331iJEiXsqquusrZt27qmH4mPj7dTp05ZkyZNgmXVjHTllVfaypUr3bxuq1Wr5kKLR2HkyJEjtmXLlmCZ0G14ZbxtJOfEiRNuO6ETAAC4iINLvXr1XNPO/Pnzbfz48a5Zp0GDBvbbb7/Zvn37XI1JgQIFwu6jkKJ1otvQ0OKt99alVEZB5Pjx48nu27Bhwyx//vzBqVSpUhn2vAEAgA+bipo1axb8u3r16i7IlC5d2j788EPLkydPlu5b//79rXfv3sF5BR3CCwAAF3GNS0KqXbnmmmtsx44drt+LOt0eOnQorIxGFXl9YnSbcJSRN3+uMvny5UsxHGkEksqETgAAIHP5KrgcPXrUdu7cacWLF7fatWtbzpw5LS4uLrh++/btrg9M/fr13bxuN23aZAcOHAiWWbhwoQsZlStXDpYJ3YZXxtsGAACIHBEdXJ566ik3zHn37t1uOPNf/vIXy549u7Vu3dr1K+nUqZNrrlm8eLHrrPvII4+4wKERRdK0aVMXUB5++GHbsGGDG+I8YMAAd+0X1ZjIY489Zt9++609/fTTtm3bNnvttddcU5SGWgMAgMgS0X1cfvjhBxdSfvnlFytSpIjddNNNbqiz/hYNWc6WLZu78JxG+Wg0kIKHRyFnzpw59vjjj7tAc+mll1r79u1tyJAhwTIaCj137lwXVMaMGWMlS5a0N998k6HQAABEoKhAIBDI6p34M1DnXNUC6foymdHfpXbfdzN8m0CkiR/ZzvyKzyguBvGZ9BlNyzk0opuKAAAAQhFcAACAbxBcAACAbxBcAACAbxBcAACAbxBcAACAbxBcAACAbxBcAACAbxBcAACAbxBcAACAbxBcAACAbxBcAACAbxBcAACAbxBcAACAbxBcAACAbxBcAACAbxBcAACAbxBcAACAbxBcAACAbxBcAACAbxBcAACAbxBcAACAbxBcAACAbxBcAACAbxBcAACAb0R0cBk2bJjVrVvX8ubNa0WLFrWWLVva9u3bw8rccsstFhUVFTY99thjYWX27NljzZs3t0suucRtp2/fvnb69OmwMkuWLLFatWpZrly5rHz58jZp0qQL8hwBAMCfJLgsXbrUunXrZqtWrbKFCxfaqVOnrGnTpnbs2LGwcl26dLG9e/cGpxEjRgTXnTlzxoWWkydP2ooVK+ydd95xoWTgwIHBMrt27XJlGjVqZOvXr7eePXta586d7ZNPPrmgzxcAAKQsh0Ww+fPnh80rcKjGJD4+3ho2bBhcrpqUmJiYJLexYMEC27p1qy1atMiKFStmNWvWtKFDh1q/fv1s0KBBFh0dbRMmTLCyZcvaqFGj3H0qVapky5cvt9GjR1tsbGwmP0sAAPCnqHFJ6PDhw+62YMGCYcsnT55shQsXtqpVq1r//v3t999/D65buXKlVatWzYUWj8LIkSNHbMuWLcEyTZo0Cdumymh5ck6cOOG2EToBAICLuMYl1NmzZ10Tzo033ugCiqdNmzZWunRpK1GihG3cuNHVpKgfzMcff+zW79u3Lyy0iDevdSmVURg5fvy45cmTJ8n+N4MHD86U5woAAHweXNTXZfPmza4JJ1TXrl2Df6tmpXjx4ta4cWPbuXOnlStXLtP2RzU7vXv3Ds4r5JQqVSrTHg8AAPikqah79+42Z84cW7x4sZUsWTLFsvXq1XO3O3bscLfq+7J///6wMt681y8muTL58uVLsrZFNPpI60MnAABwEQeXQCDgQsv06dPt008/dR1oz0WjgkQ1L1K/fn3btGmTHThwIFhGI5QUNCpXrhwsExcXF7YdldFyAAAQObJFevPQe++9Z1OmTHHXclFfFE3qdyJqDtIIIY0y2r17t82aNcvatWvnRhxVr17dldHwaQWUhx9+2DZs2OCGOA8YMMBtW7Umouu+fPvtt/b000/btm3b7LXXXrMPP/zQevXqlaXPHwAA+Ci4jB8/3o0k0kXmVIPiTVOnTnXrNZRZw5wVTipWrGh9+vSxVq1a2ezZs4PbyJ49u2tm0q1qUB566CEXboYMGRIso5qcuXPnulqWGjVquGHRb775JkOhAQCIMDkivakoJeoMq4vUnYtGHc2bNy/FMgpH69atS/M+AgCACyeia1wAAABCEVwAAIBvEFwAAIBvEFwAAIBvEFwAAIBvEFwAAIBvEFwAAIBvEFwAAIBvEFwAAIBvEFwAAIBvEFwAAIBvEFwAAIBvEFwAAIBvEFwAAIBvEFwAAIBvEFwAAIBvEFwAAIBvEFwAAIBvEFwAAIBvEFwAAIBvEFwAAIBvEFwAAIBvEFwAAIBvEFwAAIBvEFwSGDdunJUpU8Zy585t9erVs9WrV2f1LgEAgP9DcAkxdepU6927tz333HP25ZdfWo0aNSw2NtYOHDiQ1bsGAAAILuFeeukl69Kliz3yyCNWuXJlmzBhgl1yySU2ceLErN41AABgZjmyegcixcmTJy0+Pt769+8fXJYtWzZr0qSJrVy5MlH5EydOuMlz+PBhd3vkyJFM2b8zJ45nynaBSJJZn58Lgc8oLgZHMukz6m03EAicsyzB5f/8/PPPdubMGStWrFjYcs1v27YtUflhw4bZ4MGDEy0vVapUpu4n8GeW/9XHsnoXAGThZ/S3336z/Pnzp1iG4JJOqplRfxjP2bNn7ddff7VChQpZVFRUlu4bMib9K4R+//33li9fvqzeHQAJ8Bn9c1FNi0JLiRIlzlmW4PJ/ChcubNmzZ7f9+/eHLdd8TExMovK5cuVyU6gCBQpk+n7iwtIXIl+KQOTiM/rnca6aFg+dc/9PdHS01a5d2+Li4sJqUTRfv379LN03AADwv6hxCaGmn/bt21udOnXsuuuus5dfftmOHTvmRhkBAICsR3AJ8cADD9hPP/1kAwcOtH379lnNmjVt/vz5iTrs4s9PzYC6nk/C5kAAkYHP6MUrKpCasUcAAAARgD4uAADANwguAADANwguAADANwguAADANwguQBLGjRtnZcqUsdy5c1u9evVs9erVWb1LAMxs2bJl1qJFC3eFVV2lfMaMGVm9S7jACC5AAlOnTnXX9NFQyy+//NJq1KhhsbGxduDAgazeNeCip2tr6TOpHxe4ODEcGkhANSx169a1sWPHBq+grP8T5YknnrBnnnkmq3cPwP9Rjcv06dOtZcuWWb0ruICocQFCnDx50uLj461JkybBZdmyZXPzK1euzNJ9AwAQXIAwP//8s505cybR1ZI1r6spAwCyFsEFAAD4BsEFCFG4cGHLnj277d+/P2y55mNiYrJsvwAA/4vgAoSIjo622rVrW1xcXHCZOudqvn79+lm6bwAA/ndoIBENhW7fvr3VqVPHrrvuOnv55ZfdEMxHHnkkq3cNuOgdPXrUduzYEZzftWuXrV+/3goWLGhXXnlllu4bLgyGQwNJ0FDokSNHug65NWvWtFdeecUNkwaQtZYsWWKNGjVKtFw/NiZNmpQl+4QLi+ACAAB8gz4uAADANwguAADANwguAADANwguAADANwguAADANwguAADANwguAADANwguAADANwguAHzjlltusZ49e6b6CqtRUVF26NCh83rMMmXKuP/2AUBkILgAAADfILgAAADfILgA8KV//etf7n/wzps3r8XExFibNm3swIEDicp9/vnnVr16dcudO7ddf/31tnnz5rD1y5cvtwYNGliePHmsVKlS9uSTT7r/DRxAZCK4APClU6dO2dChQ23Dhg02Y8YM2717t3Xo0CFRub59+9qoUaNszZo1VqRIEWvRooW7r+zcudNuv/12a9WqlW3cuNGmTp3qgkz37t2z4BkBSI0cqSoFABGmY8eOwb+vuuoqe+WVV6xu3bp29OhRu+yyy4LrnnvuObvtttvc3++8846VLFnSpk+fbvfff78NGzbM2rZtG+zwe/XVV7vt3HzzzTZ+/HhXSwMgslDjAsCX4uPjXe3JlVde6ZqLFDZkz549YeXq168f/LtgwYJWoUIF++qrr9y8amsmTZrkgo43xcbG2tmzZ23Xrl0X+BkBSA1qXAD4jvqgKGBomjx5smsCUmDR/MmTJ1O9HdXOPProo65fS0IKRAAiD8EFgO9s27bNfvnlFxs+fLjrUCtr165NsuyqVauCIeTgwYP29ddfW6VKldx8rVq1bOvWrVa+fPkLuPcAzgdNRQB8R0EkOjraXn31Vfv2229t1qxZrqNuUoYMGWJxcXFuNJE67xYuXNhatmzp1vXr189WrFjhOuOuX7/evvnmG5s5cyadc4EIRnAB4DtqGlLflGnTplnlypVdzcuLL76YZFmt69Gjh9WuXdv27dtns2fPdqFHNEx66dKlrhZGQ6KvvfZaGzhwoJUoUeICPyMAqRUVCAQCqS4NAACQhahxAQAAvkFwAQAAvkFwAQAAvkFwAQAAvkFwAQAAvkFwAQAAvkFwAQAAvkFwAQAAvkFwAQAAvkFwAQAAvkFwAQAA5hf/D2B8SotB/8M+AAAAAElFTkSuQmCC",
      "text/plain": [
       "<Figure size 600x400 with 1 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "\n",
    "plt.figure(figsize=(6,4))\n",
    "sns.countplot(x=df['label'])\n",
    "plt.title(\"Number of Fake vs Real News Articles\")\n",
    "plt.show()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "5e0ab0c5-f088-4807-9a81-ce0436b2dbbd",
   "metadata": {},
   "outputs": [],
   "source": [
    "df['text'] = df['text'].fillna(\"\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "6522667d-57af-4c93-929b-130a2cc50179",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.feature_extraction.text import TfidfVectorizer\n",
    "\n",
    "X = df['text']\n",
    "y = df['label']\n",
    "\n",
    "tfidf = TfidfVectorizer(stop_words='english', max_features=5000)\n",
    "X_tfidf = tfidf.fit_transform(X)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "d8db165b-59a4-47e6-b1f1-397a85822884",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.model_selection import train_test_split"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "2eb7f0f9-ea16-4058-8ad4-3bf56a97d31f",
   "metadata": {},
   "outputs": [],
   "source": [
    "X_train, X_test, y_train, y_test = train_test_split(X_tfidf, y, test_size=0.2, random_state=42)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "5b52b2d8-f9b2-43eb-81de-64c76e7dbf94",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<style>#sk-container-id-1 {\n",
       "  /* Definition of color scheme common for light and dark mode */\n",
       "  --sklearn-color-text: #000;\n",
       "  --sklearn-color-text-muted: #666;\n",
       "  --sklearn-color-line: gray;\n",
       "  /* Definition of color scheme for unfitted estimators */\n",
       "  --sklearn-color-unfitted-level-0: #fff5e6;\n",
       "  --sklearn-color-unfitted-level-1: #f6e4d2;\n",
       "  --sklearn-color-unfitted-level-2: #ffe0b3;\n",
       "  --sklearn-color-unfitted-level-3: chocolate;\n",
       "  /* Definition of color scheme for fitted estimators */\n",
       "  --sklearn-color-fitted-level-0: #f0f8ff;\n",
       "  --sklearn-color-fitted-level-1: #d4ebff;\n",
       "  --sklearn-color-fitted-level-2: #b3dbfd;\n",
       "  --sklearn-color-fitted-level-3: cornflowerblue;\n",
       "\n",
       "  /* Specific color for light theme */\n",
       "  --sklearn-color-text-on-default-background: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, black)));\n",
       "  --sklearn-color-background: var(--sg-background-color, var(--theme-background, var(--jp-layout-color0, white)));\n",
       "  --sklearn-color-border-box: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, black)));\n",
       "  --sklearn-color-icon: #696969;\n",
       "\n",
       "  @media (prefers-color-scheme: dark) {\n",
       "    /* Redefinition of color scheme for dark theme */\n",
       "    --sklearn-color-text-on-default-background: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, white)));\n",
       "    --sklearn-color-background: var(--sg-background-color, var(--theme-background, var(--jp-layout-color0, #111)));\n",
       "    --sklearn-color-border-box: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, white)));\n",
       "    --sklearn-color-icon: #878787;\n",
       "  }\n",
       "}\n",
       "\n",
       "#sk-container-id-1 {\n",
       "  color: var(--sklearn-color-text);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 pre {\n",
       "  padding: 0;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 input.sk-hidden--visually {\n",
       "  border: 0;\n",
       "  clip: rect(1px 1px 1px 1px);\n",
       "  clip: rect(1px, 1px, 1px, 1px);\n",
       "  height: 1px;\n",
       "  margin: -1px;\n",
       "  overflow: hidden;\n",
       "  padding: 0;\n",
       "  position: absolute;\n",
       "  width: 1px;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-dashed-wrapped {\n",
       "  border: 1px dashed var(--sklearn-color-line);\n",
       "  margin: 0 0.4em 0.5em 0.4em;\n",
       "  box-sizing: border-box;\n",
       "  padding-bottom: 0.4em;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-container {\n",
       "  /* jupyter's `normalize.less` sets `[hidden] { display: none; }`\n",
       "     but bootstrap.min.css set `[hidden] { display: none !important; }`\n",
       "     so we also need the `!important` here to be able to override the\n",
       "     default hidden behavior on the sphinx rendered scikit-learn.org.\n",
       "     See: https://github.com/scikit-learn/scikit-learn/issues/21755 */\n",
       "  display: inline-block !important;\n",
       "  position: relative;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-text-repr-fallback {\n",
       "  display: none;\n",
       "}\n",
       "\n",
       "div.sk-parallel-item,\n",
       "div.sk-serial,\n",
       "div.sk-item {\n",
       "  /* draw centered vertical line to link estimators */\n",
       "  background-image: linear-gradient(var(--sklearn-color-text-on-default-background), var(--sklearn-color-text-on-default-background));\n",
       "  background-size: 2px 100%;\n",
       "  background-repeat: no-repeat;\n",
       "  background-position: center center;\n",
       "}\n",
       "\n",
       "/* Parallel-specific style estimator block */\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel-item::after {\n",
       "  content: \"\";\n",
       "  width: 100%;\n",
       "  border-bottom: 2px solid var(--sklearn-color-text-on-default-background);\n",
       "  flex-grow: 1;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel {\n",
       "  display: flex;\n",
       "  align-items: stretch;\n",
       "  justify-content: center;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "  position: relative;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel-item {\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel-item:first-child::after {\n",
       "  align-self: flex-end;\n",
       "  width: 50%;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel-item:last-child::after {\n",
       "  align-self: flex-start;\n",
       "  width: 50%;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel-item:only-child::after {\n",
       "  width: 0;\n",
       "}\n",
       "\n",
       "/* Serial-specific style estimator block */\n",
       "\n",
       "#sk-container-id-1 div.sk-serial {\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "  align-items: center;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "  padding-right: 1em;\n",
       "  padding-left: 1em;\n",
       "}\n",
       "\n",
       "\n",
       "/* Toggleable style: style used for estimator/Pipeline/ColumnTransformer box that is\n",
       "clickable and can be expanded/collapsed.\n",
       "- Pipeline and ColumnTransformer use this feature and define the default style\n",
       "- Estimators will overwrite some part of the style using the `sk-estimator` class\n",
       "*/\n",
       "\n",
       "/* Pipeline and ColumnTransformer style (default) */\n",
       "\n",
       "#sk-container-id-1 div.sk-toggleable {\n",
       "  /* Default theme specific background. It is overwritten whether we have a\n",
       "  specific estimator or a Pipeline/ColumnTransformer */\n",
       "  background-color: var(--sklearn-color-background);\n",
       "}\n",
       "\n",
       "/* Toggleable label */\n",
       "#sk-container-id-1 label.sk-toggleable__label {\n",
       "  cursor: pointer;\n",
       "  display: flex;\n",
       "  width: 100%;\n",
       "  margin-bottom: 0;\n",
       "  padding: 0.5em;\n",
       "  box-sizing: border-box;\n",
       "  text-align: center;\n",
       "  align-items: start;\n",
       "  justify-content: space-between;\n",
       "  gap: 0.5em;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 label.sk-toggleable__label .caption {\n",
       "  font-size: 0.6rem;\n",
       "  font-weight: lighter;\n",
       "  color: var(--sklearn-color-text-muted);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 label.sk-toggleable__label-arrow:before {\n",
       "  /* Arrow on the left of the label */\n",
       "  content: \"▸\";\n",
       "  float: left;\n",
       "  margin-right: 0.25em;\n",
       "  color: var(--sklearn-color-icon);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 label.sk-toggleable__label-arrow:hover:before {\n",
       "  color: var(--sklearn-color-text);\n",
       "}\n",
       "\n",
       "/* Toggleable content - dropdown */\n",
       "\n",
       "#sk-container-id-1 div.sk-toggleable__content {\n",
       "  display: none;\n",
       "  text-align: left;\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-toggleable__content.fitted {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-toggleable__content pre {\n",
       "  margin: 0.2em;\n",
       "  border-radius: 0.25em;\n",
       "  color: var(--sklearn-color-text);\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-toggleable__content.fitted pre {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 input.sk-toggleable__control:checked~div.sk-toggleable__content {\n",
       "  /* Expand drop-down */\n",
       "  display: block;\n",
       "  width: 100%;\n",
       "  overflow: visible;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 input.sk-toggleable__control:checked~label.sk-toggleable__label-arrow:before {\n",
       "  content: \"▾\";\n",
       "}\n",
       "\n",
       "/* Pipeline/ColumnTransformer-specific style */\n",
       "\n",
       "#sk-container-id-1 div.sk-label input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
       "  color: var(--sklearn-color-text);\n",
       "  background-color: var(--sklearn-color-unfitted-level-2);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-label.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
       "  background-color: var(--sklearn-color-fitted-level-2);\n",
       "}\n",
       "\n",
       "/* Estimator-specific style */\n",
       "\n",
       "/* Colorize estimator box */\n",
       "#sk-container-id-1 div.sk-estimator input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-2);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-estimator.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-2);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-label label.sk-toggleable__label,\n",
       "#sk-container-id-1 div.sk-label label {\n",
       "  /* The background is the default theme color */\n",
       "  color: var(--sklearn-color-text-on-default-background);\n",
       "}\n",
       "\n",
       "/* On hover, darken the color of the background */\n",
       "#sk-container-id-1 div.sk-label:hover label.sk-toggleable__label {\n",
       "  color: var(--sklearn-color-text);\n",
       "  background-color: var(--sklearn-color-unfitted-level-2);\n",
       "}\n",
       "\n",
       "/* Label box, darken color on hover, fitted */\n",
       "#sk-container-id-1 div.sk-label.fitted:hover label.sk-toggleable__label.fitted {\n",
       "  color: var(--sklearn-color-text);\n",
       "  background-color: var(--sklearn-color-fitted-level-2);\n",
       "}\n",
       "\n",
       "/* Estimator label */\n",
       "\n",
       "#sk-container-id-1 div.sk-label label {\n",
       "  font-family: monospace;\n",
       "  font-weight: bold;\n",
       "  display: inline-block;\n",
       "  line-height: 1.2em;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-label-container {\n",
       "  text-align: center;\n",
       "}\n",
       "\n",
       "/* Estimator-specific */\n",
       "#sk-container-id-1 div.sk-estimator {\n",
       "  font-family: monospace;\n",
       "  border: 1px dotted var(--sklearn-color-border-box);\n",
       "  border-radius: 0.25em;\n",
       "  box-sizing: border-box;\n",
       "  margin-bottom: 0.5em;\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-estimator.fitted {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-0);\n",
       "}\n",
       "\n",
       "/* on hover */\n",
       "#sk-container-id-1 div.sk-estimator:hover {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-2);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-estimator.fitted:hover {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-2);\n",
       "}\n",
       "\n",
       "/* Specification for estimator info (e.g. \"i\" and \"?\") */\n",
       "\n",
       "/* Common style for \"i\" and \"?\" */\n",
       "\n",
       ".sk-estimator-doc-link,\n",
       "a:link.sk-estimator-doc-link,\n",
       "a:visited.sk-estimator-doc-link {\n",
       "  float: right;\n",
       "  font-size: smaller;\n",
       "  line-height: 1em;\n",
       "  font-family: monospace;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "  border-radius: 1em;\n",
       "  height: 1em;\n",
       "  width: 1em;\n",
       "  text-decoration: none !important;\n",
       "  margin-left: 0.5em;\n",
       "  text-align: center;\n",
       "  /* unfitted */\n",
       "  border: var(--sklearn-color-unfitted-level-1) 1pt solid;\n",
       "  color: var(--sklearn-color-unfitted-level-1);\n",
       "}\n",
       "\n",
       ".sk-estimator-doc-link.fitted,\n",
       "a:link.sk-estimator-doc-link.fitted,\n",
       "a:visited.sk-estimator-doc-link.fitted {\n",
       "  /* fitted */\n",
       "  border: var(--sklearn-color-fitted-level-1) 1pt solid;\n",
       "  color: var(--sklearn-color-fitted-level-1);\n",
       "}\n",
       "\n",
       "/* On hover */\n",
       "div.sk-estimator:hover .sk-estimator-doc-link:hover,\n",
       ".sk-estimator-doc-link:hover,\n",
       "div.sk-label-container:hover .sk-estimator-doc-link:hover,\n",
       ".sk-estimator-doc-link:hover {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-3);\n",
       "  color: var(--sklearn-color-background);\n",
       "  text-decoration: none;\n",
       "}\n",
       "\n",
       "div.sk-estimator.fitted:hover .sk-estimator-doc-link.fitted:hover,\n",
       ".sk-estimator-doc-link.fitted:hover,\n",
       "div.sk-label-container:hover .sk-estimator-doc-link.fitted:hover,\n",
       ".sk-estimator-doc-link.fitted:hover {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-3);\n",
       "  color: var(--sklearn-color-background);\n",
       "  text-decoration: none;\n",
       "}\n",
       "\n",
       "/* Span, style for the box shown on hovering the info icon */\n",
       ".sk-estimator-doc-link span {\n",
       "  display: none;\n",
       "  z-index: 9999;\n",
       "  position: relative;\n",
       "  font-weight: normal;\n",
       "  right: .2ex;\n",
       "  padding: .5ex;\n",
       "  margin: .5ex;\n",
       "  width: min-content;\n",
       "  min-width: 20ex;\n",
       "  max-width: 50ex;\n",
       "  color: var(--sklearn-color-text);\n",
       "  box-shadow: 2pt 2pt 4pt #999;\n",
       "  /* unfitted */\n",
       "  background: var(--sklearn-color-unfitted-level-0);\n",
       "  border: .5pt solid var(--sklearn-color-unfitted-level-3);\n",
       "}\n",
       "\n",
       ".sk-estimator-doc-link.fitted span {\n",
       "  /* fitted */\n",
       "  background: var(--sklearn-color-fitted-level-0);\n",
       "  border: var(--sklearn-color-fitted-level-3);\n",
       "}\n",
       "\n",
       ".sk-estimator-doc-link:hover span {\n",
       "  display: block;\n",
       "}\n",
       "\n",
       "/* \"?\"-specific style due to the `<a>` HTML tag */\n",
       "\n",
       "#sk-container-id-1 a.estimator_doc_link {\n",
       "  float: right;\n",
       "  font-size: 1rem;\n",
       "  line-height: 1em;\n",
       "  font-family: monospace;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "  border-radius: 1rem;\n",
       "  height: 1rem;\n",
       "  width: 1rem;\n",
       "  text-decoration: none;\n",
       "  /* unfitted */\n",
       "  color: var(--sklearn-color-unfitted-level-1);\n",
       "  border: var(--sklearn-color-unfitted-level-1) 1pt solid;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 a.estimator_doc_link.fitted {\n",
       "  /* fitted */\n",
       "  border: var(--sklearn-color-fitted-level-1) 1pt solid;\n",
       "  color: var(--sklearn-color-fitted-level-1);\n",
       "}\n",
       "\n",
       "/* On hover */\n",
       "#sk-container-id-1 a.estimator_doc_link:hover {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-3);\n",
       "  color: var(--sklearn-color-background);\n",
       "  text-decoration: none;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 a.estimator_doc_link.fitted:hover {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-3);\n",
       "}\n",
       "\n",
       ".estimator-table summary {\n",
       "    padding: .5rem;\n",
       "    font-family: monospace;\n",
       "    cursor: pointer;\n",
       "}\n",
       "\n",
       ".estimator-table details[open] {\n",
       "    padding-left: 0.1rem;\n",
       "    padding-right: 0.1rem;\n",
       "    padding-bottom: 0.3rem;\n",
       "}\n",
       "\n",
       ".estimator-table .parameters-table {\n",
       "    margin-left: auto !important;\n",
       "    margin-right: auto !important;\n",
       "}\n",
       "\n",
       ".estimator-table .parameters-table tr:nth-child(odd) {\n",
       "    background-color: #fff;\n",
       "}\n",
       "\n",
       ".estimator-table .parameters-table tr:nth-child(even) {\n",
       "    background-color: #f6f6f6;\n",
       "}\n",
       "\n",
       ".estimator-table .parameters-table tr:hover {\n",
       "    background-color: #e0e0e0;\n",
       "}\n",
       "\n",
       ".estimator-table table td {\n",
       "    border: 1px solid rgba(106, 105, 104, 0.232);\n",
       "}\n",
       "\n",
       ".user-set td {\n",
       "    color:rgb(255, 94, 0);\n",
       "    text-align: left;\n",
       "}\n",
       "\n",
       ".user-set td.value pre {\n",
       "    color:rgb(255, 94, 0) !important;\n",
       "    background-color: transparent !important;\n",
       "}\n",
       "\n",
       ".default td {\n",
       "    color: black;\n",
       "    text-align: left;\n",
       "}\n",
       "\n",
       ".user-set td i,\n",
       ".default td i {\n",
       "    color: black;\n",
       "}\n",
       "\n",
       ".copy-paste-icon {\n",
       "    background-image: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48IS0tIUZvbnQgQXdlc29tZSBGcmVlIDYuNy4yIGJ5IEBmb250YXdlc29tZSAtIGh0dHBzOi8vZm9udGF3ZXNvbWUuY29tIExpY2Vuc2UgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbS9saWNlbnNlL2ZyZWUgQ29weXJpZ2h0IDIwMjUgRm9udGljb25zLCBJbmMuLS0+PHBhdGggZD0iTTIwOCAwTDMzMi4xIDBjMTIuNyAwIDI0LjkgNS4xIDMzLjkgMTQuMWw2Ny45IDY3LjljOSA5IDE0LjEgMjEuMiAxNC4xIDMzLjlMNDQ4IDMzNmMwIDI2LjUtMjEuNSA0OC00OCA0OGwtMTkyIDBjLTI2LjUgMC00OC0yMS41LTQ4LTQ4bDAtMjg4YzAtMjYuNSAyMS41LTQ4IDQ4LTQ4ek00OCAxMjhsODAgMCAwIDY0LTY0IDAgMCAyNTYgMTkyIDAgMC0zMiA2NCAwIDAgNDhjMCAyNi41LTIxLjUgNDgtNDggNDhMNDggNTEyYy0yNi41IDAtNDgtMjEuNS00OC00OEwwIDE3NmMwLTI2LjUgMjEuNS00OCA0OC00OHoiLz48L3N2Zz4=);\n",
       "    background-repeat: no-repeat;\n",
       "    background-size: 14px 14px;\n",
       "    background-position: 0;\n",
       "    display: inline-block;\n",
       "    width: 14px;\n",
       "    height: 14px;\n",
       "    cursor: pointer;\n",
       "}\n",
       "</style><body><div id=\"sk-container-id-1\" class=\"sk-top-container\"><div class=\"sk-text-repr-fallback\"><pre>LogisticRegression(max_iter=200)</pre><b>In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. <br />On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.</b></div><div class=\"sk-container\" hidden><div class=\"sk-item\"><div class=\"sk-estimator fitted sk-toggleable\"><input class=\"sk-toggleable__control sk-hidden--visually\" id=\"sk-estimator-id-1\" type=\"checkbox\" checked><label for=\"sk-estimator-id-1\" class=\"sk-toggleable__label fitted sk-toggleable__label-arrow\"><div><div>LogisticRegression</div></div><div><a class=\"sk-estimator-doc-link fitted\" rel=\"noreferrer\" target=\"_blank\" href=\"https://scikit-learn.org/1.7/modules/generated/sklearn.linear_model.LogisticRegression.html\">?<span>Documentation for LogisticRegression</span></a><span class=\"sk-estimator-doc-link fitted\">i<span>Fitted</span></span></div></label><div class=\"sk-toggleable__content fitted\" data-param-prefix=\"\">\n",
       "        <div class=\"estimator-table\">\n",
       "            <details>\n",
       "                <summary>Parameters</summary>\n",
       "                <table class=\"parameters-table\">\n",
       "                  <tbody>\n",
       "                    \n",
       "        <tr class=\"default\">\n",
       "            <td><i class=\"copy-paste-icon\"\n",
       "                 onclick=\"copyToClipboard('penalty',\n",
       "                          this.parentElement.nextElementSibling)\"\n",
       "            ></i></td>\n",
       "            <td class=\"param\">penalty&nbsp;</td>\n",
       "            <td class=\"value\">&#x27;l2&#x27;</td>\n",
       "        </tr>\n",
       "    \n",
       "\n",
       "        <tr class=\"default\">\n",
       "            <td><i class=\"copy-paste-icon\"\n",
       "                 onclick=\"copyToClipboard('dual',\n",
       "                          this.parentElement.nextElementSibling)\"\n",
       "            ></i></td>\n",
       "            <td class=\"param\">dual&nbsp;</td>\n",
       "            <td class=\"value\">False</td>\n",
       "        </tr>\n",
       "    \n",
       "\n",
       "        <tr class=\"default\">\n",
       "            <td><i class=\"copy-paste-icon\"\n",
       "                 onclick=\"copyToClipboard('tol',\n",
       "                          this.parentElement.nextElementSibling)\"\n",
       "            ></i></td>\n",
       "            <td class=\"param\">tol&nbsp;</td>\n",
       "            <td class=\"value\">0.0001</td>\n",
       "        </tr>\n",
       "    \n",
       "\n",
       "        <tr class=\"default\">\n",
       "            <td><i class=\"copy-paste-icon\"\n",
       "                 onclick=\"copyToClipboard('C',\n",
       "                          this.parentElement.nextElementSibling)\"\n",
       "            ></i></td>\n",
       "            <td class=\"param\">C&nbsp;</td>\n",
       "            <td class=\"value\">1.0</td>\n",
       "        </tr>\n",
       "    \n",
       "\n",
       "        <tr class=\"default\">\n",
       "            <td><i class=\"copy-paste-icon\"\n",
       "                 onclick=\"copyToClipboard('fit_intercept',\n",
       "                          this.parentElement.nextElementSibling)\"\n",
       "            ></i></td>\n",
       "            <td class=\"param\">fit_intercept&nbsp;</td>\n",
       "            <td class=\"value\">True</td>\n",
       "        </tr>\n",
       "    \n",
       "\n",
       "        <tr class=\"default\">\n",
       "            <td><i class=\"copy-paste-icon\"\n",
       "                 onclick=\"copyToClipboard('intercept_scaling',\n",
       "                          this.parentElement.nextElementSibling)\"\n",
       "            ></i></td>\n",
       "            <td class=\"param\">intercept_scaling&nbsp;</td>\n",
       "            <td class=\"value\">1</td>\n",
       "        </tr>\n",
       "    \n",
       "\n",
       "        <tr class=\"default\">\n",
       "            <td><i class=\"copy-paste-icon\"\n",
       "                 onclick=\"copyToClipboard('class_weight',\n",
       "                          this.parentElement.nextElementSibling)\"\n",
       "            ></i></td>\n",
       "            <td class=\"param\">class_weight&nbsp;</td>\n",
       "            <td class=\"value\">None</td>\n",
       "        </tr>\n",
       "    \n",
       "\n",
       "        <tr class=\"default\">\n",
       "            <td><i class=\"copy-paste-icon\"\n",
       "                 onclick=\"copyToClipboard('random_state',\n",
       "                          this.parentElement.nextElementSibling)\"\n",
       "            ></i></td>\n",
       "            <td class=\"param\">random_state&nbsp;</td>\n",
       "            <td class=\"value\">None</td>\n",
       "        </tr>\n",
       "    \n",
       "\n",
       "        <tr class=\"default\">\n",
       "            <td><i class=\"copy-paste-icon\"\n",
       "                 onclick=\"copyToClipboard('solver',\n",
       "                          this.parentElement.nextElementSibling)\"\n",
       "            ></i></td>\n",
       "            <td class=\"param\">solver&nbsp;</td>\n",
       "            <td class=\"value\">&#x27;lbfgs&#x27;</td>\n",
       "        </tr>\n",
       "    \n",
       "\n",
       "        <tr class=\"user-set\">\n",
       "            <td><i class=\"copy-paste-icon\"\n",
       "                 onclick=\"copyToClipboard('max_iter',\n",
       "                          this.parentElement.nextElementSibling)\"\n",
       "            ></i></td>\n",
       "            <td class=\"param\">max_iter&nbsp;</td>\n",
       "            <td class=\"value\">200</td>\n",
       "        </tr>\n",
       "    \n",
       "\n",
       "        <tr class=\"default\">\n",
       "            <td><i class=\"copy-paste-icon\"\n",
       "                 onclick=\"copyToClipboard('multi_class',\n",
       "                          this.parentElement.nextElementSibling)\"\n",
       "            ></i></td>\n",
       "            <td class=\"param\">multi_class&nbsp;</td>\n",
       "            <td class=\"value\">&#x27;deprecated&#x27;</td>\n",
       "        </tr>\n",
       "    \n",
       "\n",
       "        <tr class=\"default\">\n",
       "            <td><i class=\"copy-paste-icon\"\n",
       "                 onclick=\"copyToClipboard('verbose',\n",
       "                          this.parentElement.nextElementSibling)\"\n",
       "            ></i></td>\n",
       "            <td class=\"param\">verbose&nbsp;</td>\n",
       "            <td class=\"value\">0</td>\n",
       "        </tr>\n",
       "    \n",
       "\n",
       "        <tr class=\"default\">\n",
       "            <td><i class=\"copy-paste-icon\"\n",
       "                 onclick=\"copyToClipboard('warm_start',\n",
       "                          this.parentElement.nextElementSibling)\"\n",
       "            ></i></td>\n",
       "            <td class=\"param\">warm_start&nbsp;</td>\n",
       "            <td class=\"value\">False</td>\n",
       "        </tr>\n",
       "    \n",
       "\n",
       "        <tr class=\"default\">\n",
       "            <td><i class=\"copy-paste-icon\"\n",
       "                 onclick=\"copyToClipboard('n_jobs',\n",
       "                          this.parentElement.nextElementSibling)\"\n",
       "            ></i></td>\n",
       "            <td class=\"param\">n_jobs&nbsp;</td>\n",
       "            <td class=\"value\">None</td>\n",
       "        </tr>\n",
       "    \n",
       "\n",
       "        <tr class=\"default\">\n",
       "            <td><i class=\"copy-paste-icon\"\n",
       "                 onclick=\"copyToClipboard('l1_ratio',\n",
       "                          this.parentElement.nextElementSibling)\"\n",
       "            ></i></td>\n",
       "            <td class=\"param\">l1_ratio&nbsp;</td>\n",
       "            <td class=\"value\">None</td>\n",
       "        </tr>\n",
       "    \n",
       "                  </tbody>\n",
       "                </table>\n",
       "            </details>\n",
       "        </div>\n",
       "    </div></div></div></div></div><script>function copyToClipboard(text, element) {\n",
       "    // Get the parameter prefix from the closest toggleable content\n",
       "    const toggleableContent = element.closest('.sk-toggleable__content');\n",
       "    const paramPrefix = toggleableContent ? toggleableContent.dataset.paramPrefix : '';\n",
       "    const fullParamName = paramPrefix ? `${paramPrefix}${text}` : text;\n",
       "\n",
       "    const originalStyle = element.style;\n",
       "    const computedStyle = window.getComputedStyle(element);\n",
       "    const originalWidth = computedStyle.width;\n",
       "    const originalHTML = element.innerHTML.replace('Copied!', '');\n",
       "\n",
       "    navigator.clipboard.writeText(fullParamName)\n",
       "        .then(() => {\n",
       "            element.style.width = originalWidth;\n",
       "            element.style.color = 'green';\n",
       "            element.innerHTML = \"Copied!\";\n",
       "\n",
       "            setTimeout(() => {\n",
       "                element.innerHTML = originalHTML;\n",
       "                element.style = originalStyle;\n",
       "            }, 2000);\n",
       "        })\n",
       "        .catch(err => {\n",
       "            console.error('Failed to copy:', err);\n",
       "            element.style.color = 'red';\n",
       "            element.innerHTML = \"Failed!\";\n",
       "            setTimeout(() => {\n",
       "                element.innerHTML = originalHTML;\n",
       "                element.style = originalStyle;\n",
       "            }, 2000);\n",
       "        });\n",
       "    return false;\n",
       "}\n",
       "\n",
       "document.querySelectorAll('.fa-regular.fa-copy').forEach(function(element) {\n",
       "    const toggleableContent = element.closest('.sk-toggleable__content');\n",
       "    const paramPrefix = toggleableContent ? toggleableContent.dataset.paramPrefix : '';\n",
       "    const paramName = element.parentElement.nextElementSibling.textContent.trim();\n",
       "    const fullParamName = paramPrefix ? `${paramPrefix}${paramName}` : paramName;\n",
       "\n",
       "    element.setAttribute('title', fullParamName);\n",
       "});\n",
       "</script></body>"
      ],
      "text/plain": [
       "LogisticRegression(max_iter=200)"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "from sklearn.linear_model import LogisticRegression\n",
    "\n",
    "model = LogisticRegression(max_iter=200)\n",
    "model.fit(X_train, y_train)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "a4ce6faa-ef45-459b-8038-841961bf49c2",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'REAL NEWS'"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "def predict_news(text):\n",
    "    text_tfidf = tfidf.transform([text])\n",
    "    prediction = model.predict(text_tfidf)[0]\n",
    "    return \"REAL NEWS\" if prediction == 1 else \"FAKE NEWS\"\n",
    "\n",
    "predict_news(\"The president announced a new economic reform today.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "fd227f31-b68c-4177-b0d9-e23cfd8f91bc",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pickle\n",
    "\n",
    "# Save model\n",
    "with open(\"model.pkl\", \"wb\") as f:\n",
    "    pickle.dump(model, f)\n",
    "\n",
    "# Save TF-IDF vectorizer\n",
    "with open(\"tfidf.pkl\", \"wb\") as f:\n",
    "    pickle.dump(tfidf, f)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "97de629a-15a3-4196-a5d7-2bd9e21e303f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Overwriting app.py\n"
     ]
    }
   ],
   "source": [
    "%%writefile app.py\n",
    "import streamlit as st\n",
    "import pickle\n",
    "\n",
    "with open(\"model.pkl\", \"rb\") as f:\n",
    "    model = pickle.load(f)\n",
    "\n",
    "with open(\"tfidf.pkl\", \"rb\") as f:\n",
    "    tfidf = pickle.load(f)\n",
    "\n",
    "st.title(\"📰 Fake News Detection App\")\n",
    "st.write(\"Enter any news article or headline below to check if it's **Real** or **Fake**.\")\n",
    "\n",
    "user_input = st.text_area(\"Paste News Text Here:\", height=200)\n",
    "\n",
    "if st.button(\"Predict\"):\n",
    "    if user_input.strip() == \"\":\n",
    "        st.warning(\"Please enter some text before predicting.\")\n",
    "    else:\n",
    "        input_tfidf = tfidf.transform([user_input])\n",
    "        prediction = model.predict(input_tfidf)[0]\n",
    "\n",
    "        if prediction == 1:\n",
    "            st.success(\"This news is **REAL**.\")\n",
    "        else:\n",
    "            st.error(\"This news is **FAKE**.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "127c26e7-fdd2-4e99-8cfe-e896587bba8e",
   "metadata": {},
   "outputs": [],
   "source": [
    "!python -m streamlit run app.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f3ef760f-9b71-4e38-a201-b95e1c6428a8",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Fake News for testing\n",
    "# \"Fox News Bans Gene Simmons For Life For Harassing Staff Off Camera\"\n",
    "# Real News for testing\n",
    "# \"The president announced a new economic reform today\"\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
